/*
---------------------------------------------------------------------------------------
This source file is part of swgANH (Star Wars Galaxies - A New Hope - Server Emulator)
For more information, see http://www.swganh.org


Copyright (c) 2006 - 2009 The swgANH Team

---------------------------------------------------------------------------------------
*/

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Create schema swganh
--

CREATE DATABASE IF NOT EXISTS swganh;
USE swganh;

--
-- Definition of table `attributes`
--

DROP TABLE IF EXISTS `attributes`;
CREATE TABLE `attributes` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` char(255) DEFAULT NULL,
  `internal` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `attribute_internal_description` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pk_attributes_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1289 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `attributes`
--

/*!40000 ALTER TABLE `attributes` DISABLE KEYS */;
INSERT INTO `attributes` (`id`,`name`,`internal`,`attribute_internal_description`) VALUES
 (1,'volume',0,'Volume'),
 (2,'travel_departure_planet',0,'Departure Planet'),
 (3,'travel_departure_point',0,'Departure Location'),
 (4,'travel_arrival_planet',0,'Arrival Planet'),
 (5,'travel_arrival_point',0,'Arrival Location'),
 (6,'survey_range',1,'Range of Survey'),
 (7,'survey_points',1,'Survey points'),
 (8,'survey_effect',1,'Survey Effect'),
 (9,'sample_effect',1,'Sampling Effect'),
 (10,'survey_tool_resource_category',1,'Resource Type for the Survey Tool'),
 (11,'equipped',1,'Item is equipped attribute'),
 (12,'base_conversation',1,'Conversation Base Attribute'),
 (13,'npc_chat',1,'NPCs Chatter'),
 (14,'complexity',1,'Complexity'),
 (15,'craft_tool_effectiveness',0,'Tool Effectiveness'),
 (16,'serial_number',0,'Serial Number'),
 (17,'crafter',0,'Object Creator'),
 (18,'craft_tool_status',0,'Crafting Tool Status'),
 (19,'craft_tool_typemask',1,'Bitmask type for tool'),
 (20,'xp',0,'Experience'),
 (21,'xp_type',1,'Experience Type'),
 (22,'craft_tool_time',0,'Prototype Time Remaining'),
 (23,'counter_uses_remaining',0,'Uses Remaining'),
 (24,'filling',0,'Filling'),
 (25,'duration',0,'Duration'),
 (26,'attribmods',0,'Attribute Modifiers'),
 (27,'attr_action',0,'Action'),
 (28,'no_chat',1,'Keeps NPCs From Chatting'),
 (29,'quality',0,'Quality'),
 (30,'absorption',1,'Absorption Rate'),
 (31,'accelerate_entertainer_buff',0,'Inspiration of the Muse'),
 (32,'accelerate_entertainer_buff_d',0,'Reduces the amount of time it takes for an entertainer to give a buff to another player.'),
 (33,'accelerate_entertainer_buff_dur',0,'Duration'),
 (34,'accelerate_entertainer_buff_eff',0,'% Reduction'),
 (35,'accuracy',0,'Accuracy'),
 (36,'acideffectiveness',0,'Acid Effectiveness'),
 (37,'action',0,'Action'),
 (38,'action_dur',0,'Action Duration'),
 (39,'action_e',0,'Action Effectiveness'),
 (40,'actionencumbrance',0,'Action Encumbrance'),
 (41,'add_filling',0,'Filling Bonus'),
 (42,'add_flavor',0,'Flavor Bonus'),
 (43,'add_nutrition',0,'Nutrition Bonus'),
 (44,'add_quantity',0,'Quantity Bonus'),
 (45,'aggro',0,'Aggressive'),
 (46,'ai_diction',0,'Personality Chip Installed'),
 (47,'area',0,'Area Effect'),
 (48,'arm_attr',0,'Armor Attributes'),
 (49,'armor_action_encumbrance',0,'Armor Action Encumbrance'),
 (50,'armor_eff_base',0,'Base'),
 (51,'armor_eff_blast',0,'Blast'),
 (52,'armor_eff_elemental_acid',0,'Acid'),
 (53,'armor_eff_elemental_cold',0,'Cold'),
 (54,'armor_eff_elemental_electrical',0,'Electricity'),
 (55,'armor_eff_elemental_heat',0,'Heat'),
 (56,'armor_eff_energy',0,'Energy'),
 (57,'armor_eff_environmental_acid',0,'Env Acid'),
 (58,'armor_eff_environmental_cold',0,'Env Cold'),
 (59,'armor_eff_environmental_electrical',0,'Env Electrical'),
 (60,'armor_eff_environmental_heat',0,'Env Heat'),
 (61,'armor_eff_kinetic',0,'Kinetic'),
 (62,'armor_eff_restraint',0,'Lightsaber'),
 (63,'armor_eff_stun',0,'Stun'),
 (64,'armor_effectiveness',0,'Armor Effectiveness'),
 (65,'armor_health_encumbrance',0,'Armor Health Encumbrance'),
 (66,'armor_integrity',0,'Armor Integrity'),
 (67,'armor_mind_encumbrance',0,'Armor Mind Encumbrance'),
 (68,'armor_module',0,'Armor Module Rating'),
 (69,'armor_pierce_heavy',0,'Heavy'),
 (70,'armor_pierce_light',0,'Light'),
 (71,'armor_pierce_medium',0,'Medium'),
 (72,'armor_pierce_none',0,'None'),
 (73,'armor_rating',0,'Armor Rating'),
 (74,'armor_special_effectiveness',0,'Armor Special Effectiveness'),
 (75,'armor_special_integrity',0,'Armor Special Integrity'),
 (76,'armor_special_type',0,'Armor Special Type'),
 (77,'armor_toughness',0,'Armor Toughness'),
 (78,'armoreffectiveness',0,'Armor Effectiveness'),
 (79,'armorencumbrance',0,'Armor Encumbrance'),
 (80,'armorhpmax',0,'Armor'),
 (81,'armorintegrity',0,'Armor Integrity'),
 (82,'armorrating',0,'Armor Rating'),
 (83,'armorspecialeffectiveness',0,'Armor Special Effectiveness'),
 (84,'armorspecialintegrity',0,'Armor Special Integrity'),
 (85,'attack_accuracy',0,'Enhanced Accuracy'),
 (86,'attack_accuracy_d',0,'Increases attack accuracy.'),
 (87,'attack_accuracy_eff',0,'Accuracy Increase'),
 (88,'attackactioncost',0,'Attack Action Cost'),
 (89,'attackhealthcost',0,'Attack Health Cost'),
 (90,'attackmindcost',0,'Attack Mind Cost'),
 (91,'attackspeed',0,'Attack Speed'),
 (92,'attr_constitution',0,'Constitution'),
 (93,'attr_focus',0,'Focus'),
 (94,'attr_health',0,'Health'),
 (95,'attr_mind',0,'Mind'),
 (96,'attr_quickness',0,'Quickness'),
 (97,'attr_stamina',0,'Stamina'),
 (98,'attr_strength',0,'Strength'),
 (99,'attr_willpower',0,'Willpower'),
 (100,'auto_repair_power',0,'Auto-Repair Power'),
 (101,'base_effectiveness',0,'Base Effectiveness'),
 (102,'baseeffectiveness',0,'Base Effectiveness'),
 (103,'baseintegrity',0,'Integrity'),
 (104,'basetohit',0,'Base To-Hit'),
 (105,'battery_power',0,'Battery Power'),
 (106,'bio_comp_action_mod',0,'Action Bonus:'),
 (107,'bio_comp_business_accumen',0,'Business Acumen'),
 (108,'bio_comp_camouflage',0,'Camouflage'),
 (109,'bio_comp_combat_bleeding_defense',0,'Bleeding Defense'),
 (110,'bio_comp_con_mod',0,'Constitution Bonus:'),
 (111,'bio_comp_cover',0,'Taking Cover'),
 (112,'bio_comp_creature_empathy',0,'Creature Empathy'),
 (113,'bio_comp_creature_training',0,'Creature Training'),
 (114,'bio_comp_duration',0,'Duration Bonus:'),
 (115,'bio_comp_flavor',0,'Flavor Bonus:'),
 (116,'bio_comp_focus_mod',0,'Focus Bonus:'),
 (117,'bio_comp_healing_ability',0,'Medicine Use'),
 (118,'bio_comp_healing_dance_wound',0,'Wound Healing (Dancing)'),
 (119,'bio_comp_healing_injury_treatment',0,'Injury Treatment'),
 (120,'bio_comp_healing_music_wound',0,'Wound Healing (Music)'),
 (121,'bio_comp_healing_wound_treatment',0,'Wound Treatment'),
 (122,'bio_comp_health_mod',0,'Health Bonus:'),
 (123,'bio_comp_intimidate',0,'Intimidation'),
 (124,'bio_comp_mask_scent',0,'Mask Scent'),
 (125,'bio_comp_melee_defense',0,'Melee Defense'),
 (126,'bio_comp_mind_mod',0,'Mind Bonus:'),
 (127,'bio_comp_quick_mod',0,'Quickness Bonus:'),
 (128,'bio_comp_stam_mod',0,'Stamina Bonus:'),
 (129,'bio_comp_str_mod',0,'Strength Bonus:'),
 (130,'bio_comp_stun_defense',0,'Defense Vs. Stun'),
 (131,'bio_comp_take_cover',0,'Cover'),
 (132,'bio_comp_tame_aggro',0,'Taming Vicious Creatures'),
 (133,'bio_comp_tame_non_aggro',0,'Taming Wild Creatures'),
 (134,'bio_comp_warcry',0,'Warcry'),
 (135,'bio_comp_will_mod',0,'Willpower Bonus:'),
 (136,'blasteffectiveness',0,'Blast Effectiveness'),
 (137,'blastintegrity',0,'Blast Integrity'),
 (138,'bleed_resist',0,'Autocoagulation'),
 (139,'bleed_resist_d',0,'Increases resistances against bleed attacks.'),
 (140,'bleed_resist_eff',0,'% Resistance'),
 (141,'blue_rug_adhesive',0,'Blue Rug Adhesive'),
 (142,'blue_rug_cloth_patches',0,'Blue Rug Cloth Patches'),
 (143,'blue_rug_dye',0,'Blue Rug Dye'),
 (144,'blue_rug_thread_01',0,'Blue Rug Thread - First Section'),
 (145,'blue_rug_thread_02',0,'Blue Rug Thread - Second Section'),
 (146,'blue_rug_thread_03',0,'Blue Rug Thread - Third Section'),
 (147,'blue_rug_thread_04',0,'Blue Rug Thread - Fourth Section'),
 (148,'blue_rug_thread_05',0,'Blue Rug Thread - Fifth Section'),
 (149,'blue_rug_thread_06',0,'Blue Rug Thread - Sixth Section'),
 (150,'blue_rug_thread_07',0,'Blue Rug Thread - Seventh Section'),
 (151,'blunteffectiveness',0,'Blunt Effectiveness'),
 (152,'bluntintegrity',0,'Blunt Integrity'),
 (153,'bomb_level',0,'Detonation Power'),
 (154,'bone_avian',0,'Avian Bone'),
 (155,'bone_mammal',0,'Mammal Bone'),
 (156,'booster_acceleration',0,'Booster Acceleration'),
 (157,'booster_consumption',0,'Booster Energy Consumption'),
 (158,'booster_energy',0,'Booster Energy'),
 (159,'booster_recharge',0,'Booster Recharge Rate'),
 (160,'booster_speed',0,'Booster Speed'),
 (161,'broken',0,'Broken (Unslicable)'),
 (162,'buildrate',0,'Build Rate'),
 (163,'burst_run_d',0,'Burst Runs with Bonus'),
 (164,'burst_run_v1',0,'HAM Decrease'),
 (165,'burst_run_v2',0,'Recovery Decrease'),
 (166,'cap_max_energy',0,'Max Capacitor Energy'),
 (167,'cap_recharge_rate',0,'Capacitor Recharge Rate'),
 (168,'cat_armor_effectiveness',0,'Effectiveness'),
 (169,'cat_armor_encumbrance',0,'Encumbrance'),
 (170,'cat_armor_special_protection',0,'Special Protection'),
 (171,'cat_armor_vulnerability',0,'Vulnerability'),
 (172,'cat_manf_schem_ing_component',0,'Components'),
 (173,'cat_manf_schem_ing_resource',0,'Resources'),
 (174,'cat_pup',0,'Powerup'),
 (175,'cat_pup_attack_cost',0,'Powerup Attack Cost'),
 (176,'cat_skill_mod_bonus',0,'Skill Mods'),
 (177,'cat_wpn_attack_cost',0,'Special Attack Cost'),
 (178,'cat_wpn_damage',0,'Damage'),
 (179,'cat_wpn_dot_00',0,'Damage Over Time'),
 (180,'cat_wpn_dot_01',0,'Damage Over Time'),
 (181,'cat_wpn_dot_02',0,'Damage Over Time'),
 (182,'cat_wpn_rangemods',0,'Range Modifiers'),
 (183,'challenge_level',0,'Difficulty Level'),
 (184,'charge',0,'Charge'),
 (185,'charges',0,'Charges'),
 (186,'chassishitpoints',0,'Chassis Hit Points'),
 (187,'chassismass',0,'Chassis Mass Capacity'),
 (188,'chassismassmax',0,'Maximum Total Mass'),
 (189,'cleverness',0,'Cleverness'),
 (190,'cmbt_module',0,'Combat Module Rating'),
 (191,'coldeffectiveness',0,'Cold Effectiveness'),
 (192,'color',0,'Blade Color Modification'),
 (193,'combat_healing_ability',0,'Required Combat Medicine Use Skill'),
 (194,'combat_module_rating',0,'Combat Module Rating'),
 (195,'combat_rating',0,'Combat Rating'),
 (196,'con_dur',0,'Constitution Duration'),
 (197,'con_e',0,'Constitution Effectiveness'),
 (198,'condition',0,'Condition'),
 (199,'conduithpmax',0,'Maximum Conduit Hitpoints'),
 (200,'consider',0,'Combat Difficulty'),
 (201,'constitution',0,'Constitution'),
 (202,'contents',0,'Contents'),
 (203,'count',0,'Uses'),
 (204,'counter_charges_remaining',0,'Charges Remaining'),
 (205,'courage',0,'Courage'),
 (206,'craft_bonus',0,'Crafting Concentration'),
 (207,'craft_bonus_d',0,'Increases the assembly roll of the next crafting attempt.'),
 (208,'craft_bonus_eff',0,'Crafting Bonus'),
 (209,'crafted_name',0,'Crafted Name'),
 (210,'crafting_station',0,'Private Crafting Station Capability'),
 (211,'crafting_station_clothing',0,'Clothing Crafting Capability'),
 (212,'crafting_station_food',0,'Food Crafting Capability'),
 (213,'crafting_station_space',0,'Ship Component Crafting Capability'),
 (214,'crafting_station_structure',0,'Structure Crafting Capability'),
 (215,'crafting_station_weapon',0,'Weapon, Droid, and Generic Item Crafting Capability'),
 (216,'creature_action',0,'Action'),
 (217,'creature_attack',0,'Attack Speed'),
 (218,'creature_constitution',0,'Constitution'),
 (219,'creature_damage',0,'Damage'),
 (220,'creature_focus',0,'Focus'),
 (221,'creature_health',0,'Health'),
 (222,'creature_mind',0,'Mind'),
 (223,'creature_quickness',0,'Quickness'),
 (224,'creature_stamina',0,'Stamina'),
 (225,'creature_strength',0,'Strength'),
 (226,'creature_tohit',0,'To Hit'),
 (227,'creature_vitality',0,'Vitality'),
 (228,'creature_willpower',0,'Willpower'),
 (229,'crystal_owner',0,'Owner'),
 (230,'crystal_quality',0,'Quality'),
 (231,'cure_dizzy_d',0,'Has a chance of curing the dizzy state.'),
 (232,'cure_dizzy_eff',0,'% Chance to Cure'),
 (233,'cure_fire_d',0,'Has a chance of curing fire dots.'),
 (234,'cure_fire_eff',0,'% Chance to Cure'),
 (235,'curesymptomone',0,'Potency'),
 (236,'curesymptomtwo',0,'Potential'),
 (237,'custom_appearance',0,'Custom Appearance'),
 (238,'customization_cnt',0,'Customization Lifespan'),
 (239,'damage',0,'Damage'),
 (240,'damage_max',0,'Maximum Damage'),
 (241,'damage_min',0,'Minimum Damage'),
 (242,'data_module',0,'Data Module'),
 (243,'data_module_rating',0,'Data Module Rating'),
 (244,'data_volume',0,'Data Size'),
 (245,'decay_rate',0,'Decay Rate'),
 (246,'decayrate',0,'Decay Rate'),
 (247,'delay_effect',0,'Delayed Effect'),
 (248,'dependability',0,'Dependability'),
 (249,'dexterity',0,'Dexterity'),
 (250,'dna_comp_above_average',0,'Above Average'),
 (251,'dna_comp_armor_acid',0,'Acid Resistance'),
 (252,'dna_comp_armor_blast',0,'Blast Resistance'),
 (253,'dna_comp_armor_cold',0,'Cold Resistance'),
 (254,'dna_comp_armor_electric',0,'Electricity Resistance'),
 (255,'dna_comp_armor_energy',0,'Energy Resistance'),
 (256,'dna_comp_armor_heat',0,'Heat Resistance'),
 (257,'dna_comp_armor_kinetic',0,'Kinetic Resistance'),
 (258,'dna_comp_armor_rating',0,'Armor Rating'),
 (259,'dna_comp_armor_saber',0,'Lightsaber Resistance'),
 (260,'dna_comp_armor_stun',0,'Stun Resistance'),
 (261,'dna_comp_average',0,'Average'),
 (262,'dna_comp_below_average',0,'Below Average'),
 (263,'dna_comp_cleverness',0,'Cleverness'),
 (264,'dna_comp_courage',0,'Courage'),
 (265,'dna_comp_dependability',0,'Dependability'),
 (266,'dna_comp_dexterity',0,'Dexterity'),
 (267,'dna_comp_endurance',0,'Endurance'),
 (268,'dna_comp_fierceness',0,'Fierceness'),
 (269,'dna_comp_fortitude',0,'Fortitude'),
 (270,'dna_comp_hardiness',0,'Hardiness'),
 (271,'dna_comp_high',0,'High'),
 (272,'dna_comp_intellect',0,'Intellect'),
 (273,'dna_comp_low',0,'Low'),
 (274,'dna_comp_power',0,'Power'),
 (275,'dna_comp_quality',0,'Quality'),
 (276,'dna_comp_ranged_attack',0,'Ranged Attack'),
 (277,'dna_comp_source',0,'Source'),
 (278,'dna_comp_very_high',0,'Very High'),
 (279,'dna_comp_very_low',0,'Very Low'),
 (280,'dodge_attack',0,'Combat Agility'),
 (281,'dodge_attack_d',0,'Increases chance to dodge an attack.'),
 (282,'dodge_attack_dur',0,'Duration'),
 (283,'dodge_attack_eff',0,'% Chance to Dodge'),
 (284,'dot_type_bleeding',0,'Bleeding'),
 (285,'dot_type_disease',0,'Disease'),
 (286,'dot_type_fire',0,'Fire'),
 (287,'dot_type_poison',0,'Poison'),
 (288,'droid_command_speed',0,'Droid Command Speed'),
 (289,'droid_count',0,'Droid Count'),
 (290,'droid_disabled_detonate',0,'You cannot detonate a disabled droid.'),
 (291,'droid_effect_confetti',0,'Confetti Effect'),
 (292,'droid_effect_doves',0,'Avian Effect'),
 (293,'droid_effect_electric_fog',0,'Electric Fog Effect'),
 (294,'droid_effect_foam',0,'Foam Effect'),
 (295,'droid_effect_jawa_dance',0,'Dancing Jawa Effect'),
 (296,'droid_effect_mind_bloom',0,'Mind Bloom Effect'),
 (297,'droid_trap_number',0,'Charges'),
 (298,'droid_trap_type',0,'Trap Type'),
 (299,'duration_effect',0,'Duration Effect'),
 (300,'effect',0,'Effect'),
 (301,'effective_armor',0,'Armor Effectiveness'),
 (302,'effective_shields',0,'Shield Effectiveness'),
 (303,'effectiveness',0,'Effectiveness'),
 (304,'electricaleffectiveness',0,'Electrical Effectiveness'),
 (305,'elemental_acideffectiveness',0,'Elemental Acid Effectiveness'),
 (306,'elemental_coldeffectiveness',0,'Elemental Cold Effectiveness'),
 (307,'elemental_electricaleffectiveness',0,'Elemental Electrical Effectiveness'),
 (308,'elemental_heateffectiveness',0,'Elemental Heat Effectiveness'),
 (309,'elementalblasteffectiveness',0,'Elemental Blast Effectiveness'),
 (310,'elementalblastintegrity',0,'Elemental Blast Integrity'),
 (311,'elementalcoldeffectiveness',0,'Elemental Cold Effectiveness'),
 (312,'elementalenergyeffectiveness',0,'Elemental Energy Effectiveness'),
 (313,'elementalenergyintegrity',0,'Elemental Energy Integrity'),
 (314,'elementalkineticeffectiveness',0,'Elemental Kinetic Effectiveness'),
 (315,'elementalkineticintegrity',0,'Elemental Kinetic Integrity'),
 (316,'elementalstuneffectiveness',0,'Elemental Stun Effectiveness'),
 (317,'elementalstunintegrity',0,'Elemental Stun Integrity'),
 (318,'elementealheateffectiveness',0,'Elemental Heat Effectiveness'),
 (319,'endurance',0,'Endurance'),
 (320,'energy',0,'Energy'),
 (321,'energy_gen_rate',0,'Energy Generation'),
 (322,'energy_maintenance',0,'Energy Maintenance'),
 (323,'energy_per_shot',0,'Energy/Shot'),
 (324,'energy_resistance',0,'Energy Resistance'),
 (325,'energyeffectiveness',0,'Energy Effectiveness'),
 (326,'energyintegrity',0,'Energy Integrity'),
 (327,'engine_accel',0,'Acceleration'),
 (328,'engine_decel',0,'Deceleration'),
 (329,'engine_pitch',0,'Engine Pitch'),
 (330,'engine_roll',0,'Engine Roll'),
 (331,'engine_speed',0,'Engine Speed'),
 (332,'engine_yaw',0,'Engine Yaw'),
 (333,'enhanced_regen_d',0,'Enhances the effectiveness of Trandoshan regeneration.'),
 (334,'enhanced_regen_v1',0,'% Regen Bonus'),
 (335,'enhanced_vitalize_d',0,'Vitalizes a Zabrak player with an increased effectiveness.'),
 (336,'enhanced_vitalize_eff',0,'% Vitalize Bonus'),
 (337,'entangle_resistance',0,'Entangle Resistance'),
 (338,'environmental_heateffectiveness',0,'Elemental Heat Effectiveness'),
 (339,'examine_dot_apply',0,'Condition Inflicted'),
 (340,'examine_dot_apply_power',0,'Effectiveness'),
 (341,'examine_dot_attribute',0,'Attribute Affected'),
 (342,'examine_dot_cure',0,'Condition Cured'),
 (343,'examine_dot_cure_power',0,'Cure Effectiveness'),
 (344,'examine_dot_duration',0,'Duration'),
 (345,'examine_dot_potency',0,'Potency'),
 (346,'examine_duration_action',0,'Enhance Action Duration'),
 (347,'examine_duration_constitution',0,'Enhance Constitution Duration'),
 (348,'examine_duration_disease',0,'Enhance Disease Resist Duration'),
 (349,'examine_duration_health',0,'Enhance Health Duration'),
 (350,'examine_duration_poison',0,'Enhance Poison Resist Duration'),
 (351,'examine_duration_quickness',0,'Enhance Quickness Duration'),
 (352,'examine_duration_stamina',0,'Enhance Stamina Duration'),
 (353,'examine_duration_strength',0,'Enhance Strength Duration'),
 (354,'examine_enhance_action',0,'Enhance Action'),
 (355,'examine_enhance_constitution',0,'Enhance Constitution'),
 (356,'examine_enhance_disease',0,'Enhance Disease Resist'),
 (357,'examine_enhance_health',0,'Enhance Health'),
 (358,'examine_enhance_poison',0,'Enhance Poison Resist'),
 (359,'examine_enhance_quickness',0,'Enhance Quickness'),
 (360,'examine_enhance_stamina',0,'Enhance Stamina'),
 (361,'examine_enhance_strength',0,'Enhance Strength'),
 (362,'examine_extractionrate',0,'Base Extraction Rate'),
 (363,'examine_heal_absorption',0,'Absorption Rate'),
 (364,'examine_heal_area',0,'Area Effected'),
 (365,'examine_heal_charges',0,'Charges'),
 (366,'examine_heal_damage_action',0,'Heal Action Damage'),
 (367,'examine_heal_damage_health',0,'Heal Health Damage'),
 (368,'examine_heal_damage_mind',0,'Heal Mind Damage'),
 (369,'examine_heal_range',0,'Range'),
 (370,'examine_heal_shock',0,'Heal Shock'),
 (371,'examine_heal_state',0,'Heal State'),
 (372,'examine_heal_wound_action',0,'Heal Action Wound'),
 (373,'examine_heal_wound_constitution',0,'Heal Constitution Wound'),
 (374,'examine_heal_wound_focus',0,'Heal Focus Wound'),
 (375,'examine_heal_wound_health',0,'Heal Health Wound'),
 (376,'examine_heal_wound_mind',0,'Heal Mind Wound'),
 (377,'examine_heal_wound_quickness',0,'Heal Quickness Wound'),
 (378,'examine_heal_wound_stamina',0,'Heal Stamina Wound'),
 (379,'examine_heal_wound_strength',0,'Heal Strength Wound'),
 (380,'examine_heal_wound_willpower',0,'Heal Willpower Wound'),
 (381,'examine_hoppersize',0,'Storage Capacity'),
 (382,'examine_maintenance',0,'Surplus Maintenance'),
 (383,'examine_maintenance_rate',0,'Base Maintenance Rate'),
 (384,'examine_power',0,'Surplus Power'),
 (385,'examine_repair_energy',0,'Available Repair Energy'),
 (386,'examine_repair_power',0,'Available Repair Power'),
 (387,'examine_scene',0,'Can Be Built On'),
 (388,'exp_armor_hp',0,'Experimental Armor Hitpoints'),
 (389,'exp_damage',0,'Experimental Damage'),
 (390,'exp_durability',0,'Experimental Durability'),
 (391,'exp_energy',0,'Experimental Energy'),
 (392,'exp_mass',0,'Experimental Mass'),
 (393,'experience_required',0,'Required XP'),
 (394,'experiment_bonus',0,'Heightened Concentration'),
 (395,'experiment_bonus_d',0,'Increases the success rate for the next experimentation attempt.'),
 (396,'experiment_bonus_eff',0,'Experimentation Bonus'),
 (397,'extractrate',0,'Extraction Rate'),
 (398,'faction_restriction',0,'Faction Restriction'),
 (399,'factory_attribs',0,'Item Attributes'),
 (400,'factory_count',0,'Item Count'),
 (401,'ferocity',0,'Ferocity'),
 (402,'fierceness',0,'Fierceness'),
 (403,'filling_bonus',0,'Filling Bonus'),
 (404,'fire_resist',0,'Fire Resistance'),
 (405,'fire_resist_d',0,'Increases resistances against fire.'),
 (406,'fire_resist_eff',0,'% Resistance'),
 (407,'flavor',0,'Flavor'),
 (408,'flavor_bonus',0,'Flavor Bonus'),
 (409,'fltmaxammo',0,'Maximum Ammunition'),
 (410,'fltmaxdamage',0,'Maximum Damage'),
 (411,'fltmindamage',0,'Minimum Damage'),
 (412,'fltrefirerate',0,'Fire Rate'),
 (413,'focus',0,'Focus'),
 (414,'focus_dur',0,'Focus Duration'),
 (415,'focus_e',0,'Focus Effectiveness'),
 (416,'focusencumbrance',0,'Focus Encumbrance'),
 (417,'food_reduce_d',0,'Digests some of the food in your stomach.'),
 (418,'food_reduce_v1',0,'% Reduction'),
 (419,'forcecost',0,'Force Power Cost'),
 (420,'fortitude',0,'Fortitude'),
 (421,'fs_medic_pack_cure_one',0,'Primary Curative Agent'),
 (422,'fs_medic_pack_cure_two',0,'Secondary Curative Agent'),
 (423,'fs_medic_pack_symptom_one',0,'Residual Chemical Effect'),
 (424,'fs_p3_item_decay_in',0,'Full Decay In'),
 (425,'fs_p3_item_decay_rate',0,'% Decayed'),
 (426,'fs_tracking_device_assembly_bracket_01',0,'Tracking Device Assembly Bracket - First Segment'),
 (427,'fs_tracking_device_assembly_bracket_02',0,'Tracking Device Assembly Bracket - Second Segment'),
 (428,'fs_tracking_device_assembly_bracket_03',0,'Tracking Device Assembly Bracket - Third Segment'),
 (429,'fs_tracking_device_case_01',0,'Tracking Device Case - First Section'),
 (430,'fs_tracking_device_case_02',0,'Tracking Device Case - Second Section'),
 (431,'fs_tracking_device_case_03',0,'Tracking Device Case - Third Section'),
 (432,'fs_tracking_device_control_unit',0,'Control Unit [crafted]'),
 (433,'fs_tracking_device_energy_distributor',0,'Energy Distributor [crafted]'),
 (434,'fs_tracking_device_memory_module',0,'Electronics Memory Module [crafted]'),
 (435,'fs_tracking_device_sensor_suite',0,'Micro Sensor Suite [crafted]'),
 (436,'givesymptomone',0,'Residual Chemicals'),
 (437,'gong_adhesive',0,'Gong Adhesive'),
 (438,'gong_skin_back',0,'Gong Skin - Back Section'),
 (439,'gong_skin_front',0,'Gong Skin - Front Section'),
 (440,'gong_structure_01',0,'Gong Structure - First Section'),
 (441,'gong_structure_02',0,'Gong Structure - Second Section'),
 (442,'gong_structure_03',0,'Gong Structure - Third Section'),
 (443,'gong_structure_04',0,'Gong Structure - Fourth Section'),
 (444,'gong_structure_05',0,'Gong Structure - Fifth Section'),
 (445,'gong_structure_06',0,'Gong Structure - Sixth Section'),
 (446,'gong_structure_07',0,'Gong Structure - Seventh Section'),
 (447,'grid_stability',0,'Grid Stability'),
 (448,'hacked',0,'This piece of armor has been altered by a smuggler and may bring unwanted attentions from the Empire.'),
 (449,'hacked1',0,'This weapon has been altered by a smuggler and may bring unwanted attentions from the Empire.'),
 (450,'hardiness',0,'Hardiness'),
 (451,'hardness',0,'Hardness'),
 (452,'harvest_bonus_d',0,'Increases resources from harvesting.'),
 (453,'harvest_bonus_eff',0,'% Harvest Bonus'),
 (454,'harvest_power',0,'Harvest Bonus'),
 (455,'heal_recovery',0,'Heal Recovery'),
 (456,'heal_recovery_d',0,'Reduces the player\'s heal recovery time.'),
 (457,'heal_recovery_dur',0,'# of Heals Affected'),
 (458,'heal_recovery_eff',0,'Recovery Time Bonus'),
 (459,'healing_ability',0,'Required Medicine Use Skill'),
 (460,'health',0,'Health'),
 (461,'health_dur',0,'Health Duration'),
 (462,'health_e',0,'Health Effectiveness'),
 (463,'healthencumberance',0,'Health Encumberance'),
 (464,'healthencumbrance',0,'Health Encumbrance'),
 (465,'heateffectiveness',0,'Heat Effectiveness'),
 (466,'hide_bristley',0,'Bristley Hide'),
 (467,'hide_leathery',0,'Leathery Hide'),
 (468,'hide_scaley',0,'Scaley Hide'),
 (469,'hide_wooly',0,'Wooly Hide'),
 (470,'hit_points',0,'Hit Points'),
 (471,'hitpoints',0,'Unit Integrity'),
 (472,'hitpointsmax',0,'Hitpoints'),
 (473,'hoppersize',0,'Hopper Size'),
 (474,'hp',0,'Maximum Hitpoints'),
 (475,'incap_recovery',0,'Incap Recovery'),
 (476,'incap_recovery_d',0,'Reduces incapacitation recovery time.'),
 (477,'incap_recovery_eff',0,'Incap Recovery Bonus'),
 (478,'instant_effect',0,'Instant Effect'),
 (479,'intellect',0,'Intellect'),
 (480,'is_repair_droid',0,'Repair Module Installed'),
 (481,'item_required',0,'Item Needed'),
 (482,'jedi_rank_required',0,'Rank Required'),
 (483,'jedi_robe_power',0,'Max Force Power Bonus'),
 (484,'jedi_robe_regen',0,'Force Regen Bonus'),
 (485,'job_status',0,'Job Status'),
 (486,'killer',0,'Deathblows'),
 (487,'kineticeffectiveness',0,'Kinetic Effectiveness'),
 (488,'kineticintegrity',0,'Kinetic Integrity'),
 (489,'knowlege_type',0,'Knowledge Type'),
 (490,'length',0,'Length'),
 (491,'lifespan',0,'Lifespan'),
 (492,'light_table_adhesive',0,'Glass Top Table Adhesive'),
 (493,'light_table_glasstop_01',0,'Glass Top Table - Large Glass Top'),
 (494,'light_table_glasstop_02',0,'Glass Top Table - Small Glass Top'),
 (495,'light_table_structure_01',0,'Glass Top Table Base - First Section'),
 (496,'light_table_structure_02',0,'Glass Top Table Base - Second Section'),
 (497,'light_table_structure_03',0,'Glass Top Table Base - Third Section'),
 (498,'light_table_structure_04',0,'Glass Top Table Base - Fourth Section'),
 (499,'light_table_structure_05',0,'Glass Top Table Base - Fifth Section'),
 (500,'light_table_structure_06',0,'Glass Top Table Base - Sixth Section'),
 (501,'light_table_structure_07',0,'Glass Top Table Base - Seventh Section'),
 (502,'lock_mechanism',0,'Lock Mechanism'),
 (503,'manf_attribs',0,'Attributes'),
 (504,'manf_limit',0,'Manufacture Limit'),
 (505,'manufacture_count',0,'Items Manufactured'),
 (506,'manufacture_object',0,'Manufacturing Object'),
 (507,'manufacture_schematic_volume',0,'Schematic Data Size'),
 (508,'manufacture_time',0,'Time Per Object'),
 (509,'mass',0,'Mass'),
 (510,'massmax',0,'Maximum Mass'),
 (511,'max_trap_load',0,'Maximum Trap Count'),
 (512,'maxdamage',0,'Maximum Damage'),
 (513,'maxrange',0,'Maximum Range'),
 (514,'maxrangemod',0,'Maximum Range Modifier'),
 (515,'meat_avian',0,'Avian Meat'),
 (516,'meat_carnivore',0,'Carnivore Meat'),
 (517,'meat_herbivore',0,'Herbivore Meat'),
 (518,'meat_insect',0,'Insect Meat'),
 (519,'meat_reptilian',0,'Reptilian Meat'),
 (520,'meat_wild',0,'Wild Meat'),
 (521,'mechanism_quality',0,'Mechanism Quality'),
 (522,'medical_module',0,'Medical Module Rating'),
 (523,'medpower',0,'Medical Capability Rating'),
 (524,'merchant_barker',0,'Merchant Barker'),
 (525,'midrange',0,'Medium Range'),
 (526,'midrangemod',0,'Medium Range Mod'),
 (527,'mind',0,'Mind'),
 (528,'mind_dur',0,'Mind Duration'),
 (529,'mind_e',0,'Mind Effectiveness'),
 (530,'mind_heal',0,'Mind Healing'),
 (531,'mindamage',0,'Minimum Damage'),
 (532,'mindencumberance',0,'Mind Encumberance'),
 (533,'mindencumbrance',0,'Mind Encumbrance'),
 (534,'mission_details',0,'Mission Details'),
 (535,'mitigate_damage',0,'Unnatural Toughness'),
 (536,'mitigate_damage_d',0,'Reduces damage taken from attacks.'),
 (537,'mitigate_damage_dur',0,'# of Attacks Affected'),
 (538,'mitigate_damage_eff',0,'% Damage Reduction'),
 (539,'mod_idx_five',0,'Mod Index Five'),
 (540,'mod_idx_four',0,'Mod Index Four'),
 (541,'mod_idx_one',0,'Mod Index One'),
 (542,'mod_idx_six',0,'Mod Index Six'),
 (543,'mod_idx_three',0,'Mod Index Three'),
 (544,'mod_idx_two',0,'Mod Index Two'),
 (545,'mod_val_five',0,'Mod Five'),
 (546,'mod_val_four',0,'Mod Four'),
 (547,'mod_val_one',0,'Mod One'),
 (548,'mod_val_six',0,'Mod Six'),
 (549,'mod_val_three',0,'Mod Three'),
 (550,'mod_val_two',0,'Mod Two'),
 (551,'modifier',0,'Modifier'),
 (552,'new_player_vehicle_uses_left',0,'Uses Left'),
 (553,'nutrition',0,'Nutritional Value'),
 (554,'nutrition_bonus',0,'Nutrition Bonus'),
 (555,'object_type',0,'Type'),
 (556,'orange_rug_adhesive',0,'Orange Rug Adhesive'),
 (557,'orange_rug_cloth_patches',0,'Orange Rug Cloth Patches'),
 (558,'orange_rug_dye',0,'Orange Rug Dye'),
 (559,'orange_rug_thread_01',0,'Orange Rug Thread - First Section'),
 (560,'orange_rug_thread_02',0,'Orange Rug Thread - Second Section'),
 (561,'orange_rug_thread_03',0,'Orange Rug Thread - Third Section'),
 (562,'orange_rug_thread_04',0,'Orange Rug Thread - Fourth Section'),
 (563,'orange_rug_thread_05',0,'Orange Rug Thread - Fifth Section'),
 (564,'orange_rug_thread_06',0,'Orange Rug Thread - Sixth Section'),
 (565,'orange_rug_thread_07',0,'Orange Rug Thread - Seventh Section'),
 (566,'original_name',0,'Variation Of'),
 (567,'original_name_creature',0,'Type'),
 (568,'owner',0,'Master'),
 (569,'parking_spot',0,'Hangar Location:'),
 (570,'pattern',0,'Pattern'),
 (571,'performer_effects_a',0,'Type A Lighting Effects'),
 (572,'performer_effects_b',0,'Type B Lighting Effects'),
 (573,'performer_effects_c',0,'Type C Lighting Effects'),
 (574,'performer_effects_d',0,'Type D Lighting Effects'),
 (575,'performer_effects_e',0,'Type E Lighting Effects'),
 (576,'personality_module',0,'Personality Module'),
 (577,'pet_command',0,'COMMANDS'),
 (578,'pet_command_0',0,'Follow Me'),
 (579,'pet_command_1',0,'Stay'),
 (580,'pet_command_10',0,'Transfer'),
 (581,'pet_command_11',0,'Store'),
 (582,'pet_command_12',0,'Do Trick One'),
 (583,'pet_command_13',0,'Do Trick Two'),
 (584,'pet_command_14',0,'Do Trick Three'),
 (585,'pet_command_15',0,'Do Trick Four'),
 (586,'pet_command_16',0,'Group'),
 (587,'pet_command_17',0,'Follow Other'),
 (588,'pet_command_18',0,'Special Attack One'),
 (589,'pet_command_19',0,'Special Attack Two'),
 (590,'pet_command_2',0,'Guard'),
 (591,'pet_command_20',0,'Ranged Attack'),
 (592,'pet_command_21',0,'Harvest Creature'),
 (593,'pet_command_22',0,'Fire Trap Projectile'),
 (594,'pet_command_3',0,'Friend'),
 (595,'pet_command_4',0,'Attack'),
 (596,'pet_command_5',0,'Patrol'),
 (597,'pet_command_6',0,'Get Patrol Point'),
 (598,'pet_command_7',0,'Clear Patrol Points'),
 (599,'pet_command_8',0,'Wedge Formation'),
 (600,'pet_command_9',0,'Column Formation'),
 (601,'pilotskillrequired',0,'Pilot Skill Required'),
 (602,'planet',0,'Planet'),
 (603,'plant_fruit',0,'Fruit'),
 (604,'plant_growth_rate_n',0,'Growth Rate'),
 (605,'plant_health_n',0,'Health'),
 (606,'plant_nutrient_level_n',0,'Nutrient Level'),
 (607,'plant_water_level_n',0,'Water Level'),
 (608,'playback_modules',0,'Playback Tracks'),
 (609,'poison_disease_resist',0,'Enhanced Immunities'),
 (610,'poison_disease_resist_d',0,'Increases resistances against disease and poison.'),
 (611,'poison_disease_resist_eff',0,'% Resistance'),
 (612,'potency',0,'Potency'),
 (613,'power',0,'Power'),
 (614,'power_efficiency',0,'Power Efficiency'),
 (615,'power_level',0,'Capability Level'),
 (616,'pup_uses',0,'Uses Left'),
 (617,'pup_wpn_attack_cost_action',0,'Action Cost'),
 (618,'pup_wpn_attack_cost_health',0,'Health Cost'),
 (619,'pup_wpn_attack_cost_mind',0,'Mind Cost'),
 (620,'pup_wpn_attack_speed',0,'Attack Speed'),
 (621,'pup_wpn_damage_max',0,'Max Damage'),
 (622,'pup_wpn_damage_min',0,'Min Damage'),
 (623,'pup_wpn_damage_radius',0,'Damage Radius'),
 (624,'pup_wpn_range_attack_mod_max',0,'Max Range Attack Mod'),
 (625,'pup_wpn_range_attack_mod_mid',0,'Ideal Range Attack Mod'),
 (626,'pup_wpn_range_attack_mod_zero',0,'Point Blank Attack Mod'),
 (627,'pup_wpn_range_mid',0,'Ideal Range'),
 (628,'pup_wpn_wound_chance',0,'Wound Chance'),
 (629,'quantity',0,'Quantity'),
 (630,'quantity_bonus',0,'Quantity Bonus'),
 (631,'quest_details',0,'Quest Details'),
 (632,'quick_dur',0,'Quickness Duration'),
 (633,'quick_e',0,'Quickness Effectiveness'),
 (634,'quickness',0,'Quickness'),
 (635,'race_restriction',0,'Species Restriction'),
 (636,'range',0,'Effective Range'),
 (637,'reduce_clone_wounds',0,'Clone Preparation'),
 (638,'reduce_clone_wounds_d',0,'Reduces the wounds incurred by cloning.'),
 (639,'reduce_clone_wounds_eff',0,'% Reduction'),
 (640,'reduce_spice_downtime',0,'Adaptive Blood'),
 (641,'reduce_spice_downtime_d',0,'Reduces the downtime period of the next spice taken.'),
 (642,'reduce_spice_downtime_eff',0,'% Reduction'),
 (643,'refire_rate',0,'Refire Rate'),
 (644,'repair_module',0,'Repair Module'),
 (645,'repaircharges',0,'Repair Charges'),
 (646,'repairquality',0,'Functionality Rating'),
 (647,'res_bone',0,'Bone Type'),
 (648,'res_bulk',0,'Potency'),
 (649,'res_cold_resist',0,'Cold Resistance'),
 (650,'res_conductivity',0,'Conductivity'),
 (651,'res_decay_resist',0,'Decay Resistance'),
 (652,'res_flavor',0,'Flavor'),
 (653,'res_heat_resist',0,'Heat Resistance'),
 (654,'res_hide',0,'Hide Type'),
 (655,'res_malleability',0,'Malleability'),
 (656,'res_meat',0,'Meat Type'),
 (657,'res_potential_energy',0,'Potential Energy'),
 (658,'res_quality',0,'Overall quality'),
 (659,'res_shock_resistance',0,'Shock Resistance'),
 (660,'res_toughness',0,'Unit Toughness'),
 (661,'res_volume',0,'Bulk'),
 (662,'resource_class',0,'Resource Class'),
 (663,'resource_contents',0,'Resource Quantity'),
 (664,'resource_name',0,'Resource Type'),
 (665,'restraineffectiveness',0,'Lightsaber Effectiveness'),
 (666,'reuse_time',0,'Reuse Time'),
 (667,'reverseengineeringlevel',0,'Reverse Engineering Level'),
 (668,'roundsused',0,'Ammunition Efficiency'),
 (669,'sculpture_adhesive',0,'Nabooian Sculpture Adhesive'),
 (670,'sculpture_goldinlay_01',0,'Nabooian Sculpture Gold Plating - First Coating'),
 (671,'sculpture_goldinlay_02',0,'Nabooian Sculpture Gold Plating - Second Coating'),
 (672,'sculpture_structure_01',0,'Nabooian Sculpture Base - First Section'),
 (673,'sculpture_structure_02',0,'Nabooian Sculpture Base - Second Section'),
 (674,'sculpture_structure_03',0,'Nabooian Sculpture Base - Third Section'),
 (675,'sculpture_structure_04',0,'Nabooian Sculpture Base - Fourth Section'),
 (676,'sculpture_structure_05',0,'Nabooian Sculpture Base - Fifth Section'),
 (677,'sculpture_structure_06',0,'Nabooian Sculpture Base - Sixth Section'),
 (678,'sculpture_structure_07',0,'Nabooian Sculpture Base - Seventh Section'),
 (679,'shield_max_back_hp',0,'Shield Maximum Back Hitpoints'),
 (680,'shield_max_front_hp',0,'Shield Maximum Front Hitpoints'),
 (681,'shield_recharge',0,'Shield Recharge Rate'),
 (682,'ship_component',0,'Ship Component'),
 (683,'ship_component_armor',0,'Armor'),
 (684,'ship_component_booster_acceleration',0,'Acceleration'),
 (685,'ship_component_booster_energy',0,'Booster Energy'),
 (686,'ship_component_booster_energy_consumption_rate',0,'Booster Energy Consumption Rate'),
 (687,'ship_component_booster_energy_recharge_rate',0,'Booster Recharge Rate'),
 (688,'ship_component_booster_speed_maximum',0,'Top Booster Speed'),
 (689,'ship_component_capacitor_energy',0,'Capacitor Energy'),
 (690,'ship_component_capacitor_energy_recharge_rate',0,'Recharge Rate'),
 (691,'ship_component_capacitor_recharge_rate',0,'Recharge Rate'),
 (692,'ship_component_droidinterface_speed',0,'Droid Command Speed'),
 (693,'ship_component_efficiency_energy',0,'Energy Efficiency'),
 (694,'ship_component_efficiency_general',0,'General Efficiency'),
 (695,'ship_component_energy_required',0,'Reactor Energy Drain'),
 (696,'ship_component_engine_acceleration_rate',0,'Acceleration Rate'),
 (697,'ship_component_engine_deceleration_rate',0,'Deceleration Rate'),
 (698,'ship_component_engine_pitch_acceleration_rate',0,'Pitch Acceleration Rate'),
 (699,'ship_component_engine_pitch_rate_maximum',0,'Pitch Rate Maximum'),
 (700,'ship_component_engine_roll_acceleration_rate',0,'Roll Acceleration Rate'),
 (701,'ship_component_engine_roll_rate_maximum',0,'Roll Rate Maximum'),
 (702,'ship_component_engine_speed_maximum',0,'Engine Top Speed'),
 (703,'ship_component_engine_yaw_acceleration_rate',0,'Yaw Acceleration Rate'),
 (704,'ship_component_engine_yaw_rate_maximum',0,'Yaw Rate Maximum'),
 (705,'ship_component_hitpoints',0,'Hitpoints'),
 (706,'ship_component_mass',0,'Mass'),
 (707,'ship_component_reactor_generation_rate',0,'Reactor Generation Rate'),
 (708,'ship_component_shield_hitpoints_back',0,'Back Shield Hitpoints'),
 (709,'ship_component_shield_hitpoints_front',0,'Front Shield Hitpoints'),
 (710,'ship_component_shield_recharge_rate',0,'Shield Recharge Rate'),
 (711,'ship_component_weapon_ammo',0,'Ammo'),
 (712,'ship_component_weapon_damage',0,'Damage'),
 (713,'ship_component_weapon_damage_maximum',0,''),
 (714,'ship_component_weapon_damage_minimum',0,''),
 (715,'ship_component_weapon_effectiveness_armor',0,'Vs. Armor'),
 (716,'ship_component_weapon_effectiveness_shields',0,'Vs. Shields'),
 (717,'ship_component_weapon_energy_per_shot',0,'Energy/Shot'),
 (718,'ship_component_weapon_refire_rate',0,'Refire Rate'),
 (719,'ship_name',0,'Name:'),
 (720,'skill',0,'Skill'),
 (721,'skill_mod_name',0,'Skill Modifier'),
 (722,'skill_modifier_1',0,'Primary Skill Modifier'),
 (723,'skill_modifier_2',0,'Secondary Skill Modifier'),
 (724,'skill_modifier_amount',0,'Bonus'),
 (725,'skill_modifier_length',0,'Duration'),
 (726,'skill_modifier_name',0,'Skill Name'),
 (727,'skill_required',0,'Required Skill'),
 (728,'skillmodmin',0,'Skill Required'),
 (729,'slicable',0,'Slicable'),
 (730,'slow_dot_d',0,'Reduces duration of DOT effects.'),
 (731,'slow_dot_v1',0,'Reduction'),
 (732,'sockets',0,'Sockets available'),
 (733,'spec_atk_1',0,'Special Attack 1'),
 (734,'spec_atk_2',0,'Special Attack 2'),
 (735,'species0',0,'Human'),
 (736,'species1',0,'Rodian'),
 (737,'species2',0,'Trandoshan'),
 (738,'species3',0,'Mon Calamari'),
 (739,'species4',0,'Wookiee'),
 (740,'species5',0,'Bothan'),
 (741,'species6',0,'Twi\'lek'),
 (742,'species7',0,'Zabrak'),
 (743,'speciespet',0,'Pets'),
 (744,'speed',0,'Speed'),
 (745,'stalking',0,'Stalker'),
 (746,'stam_dur',0,'Stamina Duration'),
 (747,'stam_e',0,'Stamina Effectiveness'),
 (748,'stamina',0,'Stamina'),
 (749,'state_type_blinded',0,'Blinded'),
 (750,'state_type_dizzy',0,'Dizzy'),
 (751,'state_type_intimidated',0,'Intimidated'),
 (752,'state_type_stunned',0,'Stunned'),
 (753,'stationmod',0,'Functionality Rating'),
 (754,'status',0,'Status'),
 (755,'stimpack_capacity',0,'Stimpack Capacity'),
 (756,'stimpack_power',0,'Stimpack Power'),
 (757,'stimpack_speed',0,'Stimpack Delivery'),
 (758,'stomach_drink',0,'Stomach Filling (Drink)'),
 (759,'stomach_food',0,'Stomach Filling (Food)'),
 (760,'storage_module',0,'Storage Module Rating'),
 (761,'storage_module_rating',0,'Storage Module Rating'),
 (762,'str_dur',0,'Strength Duration'),
 (763,'str_e',0,'Strength Effectiveness'),
 (764,'strength',0,'Strength'),
 (765,'struct_module',0,'Stucture Maintenance Rating'),
 (766,'struct_module_rating',0,'Stucture Maintenance Rating'),
 (767,'stuneffectiveness',0,'Stun Effectiveness'),
 (768,'stunintegrity',0,'Stun Integrity'),
 (769,'system_redundancy',0,'System Redundancy'),
 (770,'system_response',0,'System Response'),
 (771,'tamable',0,'Tamable'),
 (772,'time_remaining',0,'Reuse Time'),
 (773,'trap_bonus',0,'Trapping Bonus'),
 (774,'travel_arrival_dungeon',0,'Arrival Location'),
 (775,'type',0,'Type'),
 (776,'usemodifier',0,'Quality'),
 (777,'waypoint_active',0,'Active'),
 (778,'waypoint_planet',0,'Planet'),
 (779,'waypoint_position',0,'Position'),
 (780,'waypoint_region',0,'Region'),
 (781,'weapon_cert_status',0,'Certified'),
 (782,'will',0,'Will'),
 (783,'will_dur',0,'Willpower Duration'),
 (784,'will_e',0,'Willpower Effectiveness'),
 (785,'willpower',0,'Willpower'),
 (786,'wookiee_roar_d',0,'Enhances the next Wookiee roar.'),
 (787,'wookiee_roar_v1',0,'Roar Enhancement'),
 (788,'woundchance',0,'Wound Chance'),
 (789,'wpn_armor_pierce_rating',0,'Armor Piercing'),
 (790,'wpn_attack_cost_action',0,'Special Move Action Cost'),
 (791,'wpn_attack_cost_health',0,'Special Move Health Cost'),
 (792,'wpn_attack_cost_mind',0,'Special Move Mind Cost'),
 (793,'wpn_attack_speed',0,'Attack Speed'),
 (794,'wpn_attr',0,'Weapon Attributes'),
 (795,'wpn_comp_damage_max',0,'Maximum Damage'),
 (796,'wpn_comp_damage_min',0,'Minimum Damge'),
 (797,'wpn_damage_max',0,'Max'),
 (798,'wpn_damage_min',0,'Min'),
 (799,'wpn_damage_radius',0,'Radius'),
 (800,'wpn_damage_type',0,'Type'),
 (801,'wpn_dot_attrib',0,'Attribute'),
 (802,'wpn_dot_duration',0,'Duration'),
 (803,'wpn_dot_potency',0,'Potency'),
 (804,'wpn_dot_strength',0,'Strength'),
 (805,'wpn_dot_type',0,'Type'),
 (806,'wpn_dot_uses',0,'Uses'),
 (807,'wpn_range_attack_mod_max',0,'Maximum Range Mod'),
 (808,'wpn_range_attack_mod_mid',0,'Ideal Range Mod'),
 (809,'wpn_range_attack_mod_zero',0,'Zero Range Mod'),
 (810,'wpn_range_attack_mods',0,'Range Attack Mods'),
 (811,'wpn_range_max',0,'Max'),
 (812,'wpn_range_mid',0,'Ideal'),
 (813,'wpn_range_zero',0,'Point Blank'),
 (814,'wpn_wound_chance',0,'Wound'),
 (815,'xp_increase',0,'Enhanced Learning'),
 (816,'xp_increase_d',0,'Increases xp gain for a short time (does not affect crafting).'),
 (817,'xp_increase_dur',0,'Grants Enhanced'),
 (818,'xp_increase_eff',0,'% Bonus'),
 (819,'zerorangemod',0,'Minimum Range Modifier'),
 (820,'data_module_cert_needed',0,'Pilot\'s Required Astromech Certification'),
 (821,'droid_command_program_size',0,'Droid Program Size'),
 (822,'droid_program_expended_memory',0,'Currently Used Memory'),
 (823,'description',0,'Description'),
 (824,'fltarmoreffectiveness',0,'Armor Effectiveness'),
 (825,'fltshieldeffectiveness',0,'Shield Effectiveness'),
 (826,'chaff_effectiveness_min',0,'Minimum Chaff Effectiveness'),
 (827,'chaff_effectiveness_max',0,'Maximum Chaff Effectiveness'),
 (828,'fltmineffectiveness',0,'Chaff Minimum Effectiveness'),
 (829,'fltmaxeffectiveness',0,'Chaff Maximum Effectiveness'),
 (830,'repairpoints',0,'Repair Points'),
 (831,'ammo',0,'Ammunition'),
 (832,'droid_program_loaded',0,'Loaded Droid Program(s) Include'),
 (833,'droid_program',0,'program'),
 (834,'amount',0,'Amount'),
 (835,'droid_command_name',0,'Droid Command Name'),
 (836,'meat_domesticated',0,'Domesticated Meat'),
 (837,'attribmods.@obj_attr_n:attr_action',0,'test'),
 (838,'attribmods.@obj_attr_n:duration_effect',0,'test2'),
 (839,'absorption_fire',0,'Fire Absorption'),
 (840,'absorption_poison',0,'Poison Absorption'),
 (841,'advanced_assembly',0,'Advanced Assembly'),
 (842,'advanced_ship_experimentation',0,'Advanced Component Experimentation'),
 (843,'advertising',0,'Advertising'),
 (844,'aim',0,'General Ranged Aiming'),
 (845,'alert',0,'Alertness'),
 (846,'anti_blind',0,'Anti-Blind'),
 (847,'anti_dizzy',0,'Anti-Dizzy'),
 (848,'anti_intimidate',0,'Anti-Intimidate'),
 (849,'anti_shock',0,'Anti-Shock'),
 (850,'anti_stun',0,'Anti-Stun'),
 (851,'armor_assembly',0,'Armor Assembly'),
 (852,'armor_complexity',0,'Armor Complexity'),
 (853,'armor_customization',0,'Armor Customization'),
 (854,'armor_experimentation',0,'Armor Experimentation'),
 (855,'armor_repair',0,'Armor Repair'),
 (856,'artisan_clothing_customization',0,'Artisan Clothing Customization'),
 (857,'berserk',0,'Berserk'),
 (858,'bio_engineer_assembly',0,'Bio-Engineer Assembly'),
 (859,'bio_engineer_experimentation',0,'Bio-Engineer Experimentation'),
 (860,'blind_defense',0,'Defense Vs. Blind'),
 (861,'block',0,'Block'),
 (862,'body',0,'Bodyform'),
 (863,'booster_assembly',0,'Booster Assembly'),
 (864,'booster_experimentation',0,'Booster Experimentation'),
 (865,'bounty_mission_level',0,'Bounty Mission Difficulty'),
 (866,'burst_run',0,'Burst Run Efficiency'),
 (867,'business_acumen',0,'Business Acumen'),
 (868,'camouflage',0,'Camouflage'),
 (869,'camp',0,'Camping'),
 (870,'camp_advanced',0,'Advanced Camping'),
 (871,'camp_repel_creature',0,'Repel Creatures'),
 (872,'camprepelcreature',0,'Camping - Repel Creatures'),
 (873,'carbine_acccuracy',0,'Carbine Accuracy'),
 (874,'carbine_accuracy',0,'Carbine Accuracy'),
 (875,'carbine_aim',0,'Carbine Aiming'),
 (876,'carbine_counterattack',0,'Carbine Counterattacks'),
 (877,'carbine_damage',0,'Carbine Damage'),
 (878,'carbine_hit_while_moving',0,'Carbine Accuracy While Moving'),
 (879,'carbine_kneeling',0,'Carbine Accuracy While Kneeling'),
 (880,'carbine_prone',0,'Carbine Accuracy While Prone'),
 (881,'carbine_speed',0,'Carbine Speed'),
 (882,'carbine_standing',0,'Carbine Accuracy While Standing'),
 (883,'center_of_being_duration_onehandmelee',0,'One-handed Center Of Being Duration'),
 (884,'center_of_being_duration_polearm',0,'Polearm Center Of Being Duration'),
 (885,'center_of_being_duration_twohandmelee',0,'Two-handed melee Center of Being'),
 (886,'center_of_being_duration_unarmed',0,'Unarmed Center Of Being Duration'),
 (887,'chassis_assembly',0,'Chassis Assembly'),
 (888,'chassis_experimentation',0,'Chassis Experimentation'),
 (889,'clothing_assembly',0,'Clothing Assembly'),
 (890,'clothing_complexity',0,'Clothing Complexity'),
 (891,'clothing_customization',0,'Clothing Customization'),
 (892,'clothing_experimentation',0,'Clothing Experimentation'),
 (893,'clothing_repair',0,'Clothing Repair'),
 (894,'combat_bleeding_defense',0,'Combat Bleeding Defense'),
 (895,'combat_equilibrium',0,'Combat Equilibrium'),
 (896,'combat_equillibrium',0,'Combat Equilibrium'),
 (897,'combat_haste',0,'Combat Haste'),
 (899,'combat_medic_effectiveness',0,'Combat Medic Effectiveness'),
 (900,'combat_medicine_assembly',0,'Combat Medicine Assembly'),
 (901,'combat_medicine_experimentation',0,'Combat Medicine Experimentation'),
 (902,'conceal_contraband',0,'Contraband Concealment'),
 (903,'counterattack',0,'Counterattack'),
 (904,'cover',0,'Taking Cover'),
 (905,'crafting_repair',0,'Repair'),
 (906,'creature_assembly',0,'Creature Assembly'),
 (907,'creature_empathy',0,'Creature Empathy'),
 (908,'creature_experimentation',0,'Creature Experimentation'),
 (909,'creature_harvesting',0,'Creature Harvesting'),
 (910,'creature_hit_bonus',0,'Creature To-Hit Bonus'),
 (911,'creature_knowledge',0,'Creature Knowledge'),
 (912,'creature_management',0,'Creature Management'),
 (913,'creature_training',0,'Creature Training'),
 (914,'creatureknowledge',0,'Creature Knowledge'),
 (915,'dance_heal_injury',0,'Healing with Dance'),
 (916,'defense_reverse',0,'Defense Reverse Engineering'),
 (917,'disguise_effectiveness',0,'Disguising'),
 (918,'dissipation_bleeding',0,'Bleeding Dissipation'),
 (919,'dissipation_disease',0,'Disease Dissipation'),
 (920,'dissipation_fire',0,'Fire Dissipation'),
 (921,'dissipation_poison',0,'Poison Dissipation'),
 (922,'dizzy_defense',0,'Defense Vs. Dizzy'),
 (923,'dna_harvesting',0,'DNA Harvesting'),
 (924,'dodge',0,'Dodge'),
 (925,'domestic_assembly',0,'Domestic Arts Assembly'),
 (926,'droid_assembly',0,'Droid Assembly'),
 (927,'droid_complexity',0,'Droid Complexity'),
 (928,'droid_customization',0,'Droid Customization'),
 (929,'droid_experimentation',0,'Droid Experimentation'),
 (930,'droid_find_chance',0,'Droid Precision'),
 (931,'droid_find_speed',0,'Droid Speed'),
 (932,'droid_track_chance',0,'Tracking Droid Effectiveness'),
 (933,'droid_track_speed',0,'Droid Tracking Speed'),
 (934,'droid_tracks',0,'Tracking Droids'),
 (935,'engine_assembly',0,'Engine Assembly'),
 (936,'engine_experimentation',0,'Engine Experimentation'),
 (937,'engineering_assembly',0,'Engineering Assembly'),
 (938,'engineering_reverse',0,'Chassis/Armor Reverse Engineering'),
 (939,'face',0,'Face-form'),
 (940,'factory_efficiency',0,'Factory Efficiency'),
 (941,'factory_speed',0,'Factory Speed'),
 (942,'farm_efficiency',0,'Farm Efficiency'),
 (943,'farm_maintenance',0,'Farm Maintenance'),
 (944,'farm_management',0,'Farm Management'),
 (945,'farm_produce_flora',0,'Flora Production'),
 (946,'farm_produce_livestock',0,'Livestock Production'),
 (947,'farm_speed',0,'Farm Production Speed'),
 (948,'feign_death',0,'Feign Death'),
 (949,'firearm_assembly',0,'Firearm Assembly'),
 (950,'firearm_complexity',0,'Firearm Complexity'),
 (951,'firearm_experimentation',0,'Firearm Experimentation'),
 (952,'flora_harvester_efficiency',0,'Flora Harvester Efficiency'),
 (953,'flora_harvester_maintenance',0,'Flora Harvester Maintenance'),
 (954,'flora_harvester_speed',0,'Flora Harvester Speed'),
 (955,'food_assembly',0,'Food Assembly'),
 (956,'food_complexity',0,'Food Complexity'),
 (957,'food_experimentation',0,'Food Experimentation'),
 (958,'foraging',0,'Foraging'),
 (959,'force_absorb',0,'Force Absorb'),
 (960,'force_armor',0,'Force Armor'),
 (961,'force_assembly',0,'Force Assembly'),
 (962,'force_choke',0,'Force Choke'),
 (963,'force_control_dark',0,'Force Control: Dark'),
 (964,'force_control_light',0,'Force Control: Light'),
 (965,'force_defense',0,'Force Defense'),
 (966,'force_experimentation',0,'Force Experimentation'),
 (967,'force_failure_reduction',0,'Crafting Technique'),
 (968,'force_feedback',0,'Force Feedback'),
 (969,'force_luck',0,'Luck'),
 (970,'force_manipulation_dark',0,'Force Manipulation: Dark'),
 (971,'force_manipulation_light',0,'Force Manipulation: Light'),
 (972,'force_persuade',0,'Persuasion'),
 (973,'force_power_dark',0,'Force Power: Dark'),
 (974,'force_power_light',0,'Force Power: Light'),
 (975,'force_repair_bonus',0,'Force Repair Bonus'),
 (976,'force_run',0,'Force Run'),
 (977,'force_shield',0,'Force Shield'),
 (978,'force_vehicle_control',0,'Force Vehicular Control'),
 (979,'force_vehicle_speed',0,'Force Vehicular Acceleration'),
 (980,'forceintimidate_accuracy',0,'Force Intimidate Accuracy'),
 (981,'forceknockdown_accuracy',0,'Force Knockdown Accuracy'),
 (982,'forcelightning_accuracy',0,'Force Lightning Accuracy'),
 (983,'forcethrow_accuracy',0,'Force Throw Accuracy'),
 (984,'forceweaken_accuracy',0,'Force Weaken Accuracy'),
 (985,'frs_dark_envy',0,'Dark Force: Envy'),
 (986,'frs_dark_suffering',0,'Dark Force: Suffering'),
 (987,'frs_dark_vengeance',0,'Dark Force: Vengeance'),
 (988,'frs_light_serenity',0,'Light Force: Serenity'),
 (989,'frs_light_vigilance',0,'Light Force: Vigilance'),
 (990,'frs_light_wisdom',0,'Light Force: Wisdom'),
 (991,'general_assembly',0,'Artisan Assembly'),
 (992,'general_damage',0,'Damage Healing'),
 (993,'general_experimentation',0,'Artisan Experimentation'),
 (994,'general_wound',0,'Wound Healing'),
 (995,'grenade_assembly',0,'Grenade Assembly'),
 (996,'grenade_experimentation',0,'Grenade Experimentation'),
 (997,'group_burst_run',0,'Group Burst Run Efficiency'),
 (998,'group_defense',0,'Group Defense Bonus'),
 (999,'group_melee_defense',0,'Group Melee Defense'),
 (1000,'group_offense',0,'Group Offense Bonus'),
 (1001,'group_ranged_defense',0,'Group Ranged Defense'),
 (1002,'group_slope_move',0,'Group Terrain Negotiation'),
 (1003,'hair',0,'Hair Styling'),
 (1004,'harvester_efficiency',0,'Harvester Efficiency'),
 (1005,'harvester_maintenance',0,'Harvester Maintenance'),
 (1006,'harvester_speed',0,'Harvester Speed'),
 (1007,'heal_creature_wound',0,'Creature Wound Healing'),
 (1008,'healer_accuracy',0,'Ranged Healing Accuracy'),
 (1009,'healer_speed',0,'Ranged Healing Speed'),
 (1011,'healing_dance_ability',0,'Dance Knowledge'),
 (1012,'healing_dance_mind',0,'Dancing Mind Enhancement'),
 (1013,'healing_dance_shock',0,'Battle Fatigue Healing (Dancing)'),
 (1014,'healing_dance_wound',0,'Wound Healing (Dancing)'),
 (1015,'healing_injury_speed',0,'Injury Treatment Speed'),
 (1016,'healing_injury_treatment',0,'Injury Treatment'),
 (1017,'healing_music_ability',0,'Music Knowledge'),
 (1018,'healing_music_mind',0,'Musical Mind Enhancement'),
 (1019,'healing_music_shock',0,'Battle Fatigue Healing (Music)'),
 (1020,'healing_music_wound',0,'Wound Healing (Music)'),
 (1021,'healing_range',0,'Healing Range'),
 (1022,'healing_range_speed',0,'Ranged Injury Treatment Speed'),
 (1023,'healing_wound_speed',0,'Wound Treatment Speed'),
 (1024,'healing_wound_treatment',0,'Wound Treatment'),
 (1025,'heavy_acid_beam_accuracy',0,'Heavy Acid Beam Accuracy'),
 (1026,'heavy_acid_beam_speed',0,'Heavy Acid Beam Speed'),
 (1027,'heavy_acid_rifle_accuracy',0,'Heavy Acid Rifle Accuracy'),
 (1028,'heavy_acid_rifle_speed',0,'Heavy Acid Rifle Speed'),
 (1029,'heavy_flame_thrower_accuracy',0,'Flamethrower Accuracy'),
 (1030,'heavy_flame_thrower_speed',0,'Flamethrower Speed'),
 (1031,'heavy_lighting_rifle_accuracy',0,'Light Lightning Cannon Accuracy'),
 (1032,'heavy_lightning_beam_accuracy',0,'Heavy Lightning Beam Accuracy'),
 (1033,'heavy_lightning_beam_speed',0,'Heavy Lightning Beam Speed'),
 (1034,'heavy_lightning_rifle_accuracy',0,'Light Lightning Cannon Accuracy'),
 (1035,'heavy_particle_beam_accuracy',0,'Heavy Particle Beam Accuracy'),
 (1036,'heavy_particle_beam_speed',0,'Heavy Particle Beam Speed'),
 (1037,'heavy_rifle_acid_accuracy',0,'Heavy Acid Rifle Accuracy'),
 (1038,'heavy_rifle_acid_speed',0,'Heavy Acid Rifle Speed'),
 (1039,'heavy_rifle_lighting_accuracy',0,'Light Lightning Cannon Accuracy'),
 (1040,'heavy_rifle_lightning_accuracy',0,'Light Lightning Cannon Accuracy'),
 (1041,'heavy_rifle_lightning_speed',0,'Light Lightning Cannon Speed'),
 (1042,'heavy_rocket_launcher_accuracy',0,'Heavy Rocket Launcher Accuracy'),
 (1043,'heavy_rocket_launcher_speed',0,'Heavy Rocket Launcher Speed'),
 (1044,'heavyweapon_accuracy',0,'Heavy Weapon Accuracy'),
 (1045,'heavyweapon_speed',0,'Heavy Weapon Speed'),
 (1046,'hiring',0,'Hiring'),
 (1047,'innate_equilibrium',0,'Equilibrium'),
 (1048,'innate_regeneration',0,'Regeneration'),
 (1049,'innate_roar',0,'Wookiee Roar'),
 (1050,'innate_vitalize',0,'Vitalize'),
 (1051,'instrument_assembly',0,'Instrument Assembly'),
 (1052,'intimidate',0,'Intimidation'),
 (1053,'intimidate_defense',0,'Defense Vs. Intimidate'),
 (1054,'jedi_force_power_max',0,'Force Power Max'),
 (1055,'jedi_force_power_regen',0,'Force Power Regeneration'),
 (1056,'jedi_saber_assembly',0,'Lightsaber Assembly'),
 (1057,'jedi_saber_experimentation',0,'Lightsaber Experimentation'),
 (1058,'jedi_state_defense',0,'Jedi State Defense'),
 (1059,'jedi_toughness',0,'Jedi Toughness'),
 (1060,'keep_creature',0,'Additional Pets'),
 (1061,'knockdown_defense',0,'Defense Vs. Knockdown'),
 (1062,'language_all_comprehend',0,'Language Comprehension'),
 (1063,'language_basic_comprehend',0,'Basic (Comprehension)'),
 (1064,'language_basic_speak',0,'Basic (Speech)'),
 (1065,'language_bothan',0,'Bothese'),
 (1066,'language_bothan_comprehend',0,'Bothese (Comprehension)'),
 (1067,'language_bothan_speak',0,'Bothese (Speech)'),
 (1068,'language_ithorian',0,'Ithorian'),
 (1069,'language_ithorian_comprehend',0,'Ithorian (Comprehension)'),
 (1070,'language_ithorian_speak',0,'Ithorian (Speech)'),
 (1071,'language_lekku',0,'Lekku'),
 (1072,'language_lekku_comprehend',0,'Lekku (Comprehension)'),
 (1073,'language_lekku_speak',0,'Lekku (Silent Speech)'),
 (1074,'language_moncalamari',0,'Mon Calamarian'),
 (1075,'language_moncalamari_comprehend',0,'Mon Calamarian (Comprehension)'),
 (1076,'language_moncalamari_speak',0,'Mon Calamarian (Speech)'),
 (1077,'language_rodian',0,'Rodese'),
 (1078,'language_rodian_comprehend',0,'Rodese (Comprehension)'),
 (1079,'language_rodian_speak',0,'Rodese (Speech)'),
 (1080,'language_sullustan',0,'Sullustan'),
 (1081,'language_sullustan_comprehend',0,'Sullustan (Comprehension)'),
 (1082,'language_sullustan_speak',0,'Sullustan (Speech)'),
 (1083,'language_trandoshan',0,'Dosh'),
 (1084,'language_trandoshan_comprehend',0,'Dosh (Comprehension)'),
 (1085,'language_trandoshan_speak',0,'Dosh (Speech)'),
 (1086,'language_twilek',0,'Ryl'),
 (1087,'language_twilek_comprehend',0,'Ryl (Comprehension)'),
 (1088,'language_twilek_speak',0,'Ryl (Speech)'),
 (1089,'language_wookiee',0,'Shyriiwook'),
 (1090,'language_wookiee_comprehend',0,'Shyriiwook (Comprehension)'),
 (1091,'language_wookiee_speak',0,'Shyriiwook (Speech)'),
 (1092,'language_zabrak',0,'Zabrak'),
 (1093,'language_zabrak_comprehend',0,'Zabrak (Comprehension)'),
 (1094,'language_zabrak_speak',0,'Zabrak (Speech)'),
 (1095,'leadership',0,'Leadership'),
 (1096,'light_lightning_cannon_accuracy',0,'Light Lightning Cannon Accuracy'),
 (1097,'lightning',0,'Force Lightning'),
 (1098,'lightsaber_toughness',0,'Lightsaber Toughness'),
 (1099,'manage_vendor',0,'Vendors'),
 (1100,'markings',0,'Marking Design'),
 (1101,'mask_scent',0,'Mask Scent'),
 (1102,'medical_foraging',0,'Medical Foraging'),
 (1103,'medicine_assembly',0,'Medicine Assembly'),
 (1104,'medicine_complexity',0,'Crafting Medicine Complexity'),
 (1105,'medicine_experimentation',0,'Medicine Experimentation'),
 (1106,'meditate',0,'Meditate'),
 (1107,'melee_accuracy',0,'Enhanced Melee Accuracy'),
 (1108,'melee_assembly',0,'Melee Weapon Assembly'),
 (1109,'melee_complexity',0,'Melee Weapon Complexity'),
 (1110,'melee_defense',0,'Melee Defense'),
 (1111,'melee_experimentation',0,'Melee Experimentation'),
 (1112,'melee_speed',0,'Enhanced Melee Speed'),
 (1113,'mental',0,'Force Psyche'),
 (1114,'mindblast_accuracy',0,'Mind Blast Accuracy'),
 (1115,'missile_launching',0,'Missile Launching Skill'),
 (1116,'morale_management',0,'Morale Management'),
 (1117,'mountedcreature',0,'Mounted Creature'),
 (1118,'munition_assembly',0,'Munition Assembly'),
 (1119,'munition_complexity',0,'Munition Complexity'),
 (1120,'munition_experimentation',0,'Munition Experimentation'),
 (1121,'music_heal_injury',0,'Healing with Music'),
 (1122,'offensive_strategy',0,'Offensive Strategy'),
 (1123,'onehandlightsaber_accuracy',0,'One-handed Lightsaber Accuracy'),
 (1124,'onehandlightsaber_speed',0,'One-handed Lightsaber Speed'),
 (1125,'onehandlightsaber_toughness',0,'One-handed Lightsaber Toughness'),
 (1126,'onehandmelee_accuracy',0,'One-handed Weapon Accuracy'),
 (1127,'onehandmelee_center_of_being_efficacy',0,'One-handed Melee Center Of Being Efficacy'),
 (1128,'onehandmelee_counter_attack',0,'One-handed Weapon Counter Attack'),
 (1129,'onehandmelee_damage',0,'One-handed Melee Damage'),
 (1130,'onehandmelee_evasion',0,'One-handed Weapon Evasion'),
 (1131,'onehandmelee_speed',0,'One-handed Weapon Speed'),
 (1132,'onehandmelee_toughness',0,'One-handed Melee Toughness'),
 (1133,'onehandmeleeaccuracy',0,'One-handed Weapon Accuracy'),
 (1134,'onehandpolearm',0,'One Handed Pole Arm'),
 (1135,'onehandtechnique',0,'One Handed Technique'),
 (1136,'persuade_bribe',0,'Bribery'),
 (1137,'persuade_lie',0,'Pursuasion'),
 (1138,'pilot_special_tactics',0,'Pilot Special Tactics'),
 (1139,'pistol_accuracy',0,'Pistol Accuracy'),
 (1140,'pistol_accuracy_while_standing',0,'Pistol Accuracy While Standing'),
 (1141,'pistol_aim',0,'Pistol Aiming'),
 (1142,'pistol_counterattack',0,'Pistol Counter Attack'),
 (1143,'pistol_damage',0,'Pistol Damage'),
 (1144,'pistol_hit_while_moving',0,'Pistol Accuracy While Moving'),
 (1145,'pistol_kneeling',0,'Pistol Accuracy While Kneeling'),
 (1146,'pistol_prone',0,'Pistol Accuracy While Prone'),
 (1147,'pistol_speed',0,'Pistol Speed'),
 (1148,'pistol_standing',0,'Pistol Accuracy While Standing'),
 (1149,'polearm_accuracy',0,'Polearm Accuracy'),
 (1150,'polearm_center_of_being_efficacy',0,'Polearm Center Of Being Efficacy'),
 (1151,'polearm_counter_attack',0,'Polearm Counter Attack'),
 (1152,'polearm_evasion',0,'Polearm Evasion'),
 (1153,'polearm_speed',0,'Polearm Speed'),
 (1154,'polearm_toughness',0,'Polearm Toughness'),
 (1155,'polearmlightsaber_accuracy',0,'Double-Bladed Lightsaber Accuracy'),
 (1156,'polearmlightsaber_speed',0,'Double-Bladed Lightsaber Speed'),
 (1157,'polearmlightsaber_toughness',0,'Double-Bladed Lightsaber Toughness'),
 (1158,'posture_change_down_defense',0,'Defense Vs. Posture Change (Down)'),
 (1159,'posture_change_up_defense',0,'Defense Vs. Posture Change (Up)'),
 (1160,'power_systems',0,'Power Systems'),
 (1161,'power_systems_experimentation',0,'Power Systems Experimentation'),
 (1162,'private_innage_regeneration',0,'Regeneration'),
 (1163,'private_innate_equilibrium',0,'Equilibrium'),
 (1164,'private_innate_regeneration',0,'Regeneration'),
 (1165,'private_innate_roar',0,'Wookiee Roar'),
 (1166,'private_innate_vitalize',0,'Vitalize'),
 (1167,'propulsion_reverse',0,'Propulsion Reverse Engineering'),
 (1168,'rally',0,'Rally Shot Bonus'),
 (1169,'ranged_accuracy',0,'Enhanced Ranged Accuracy'),
 (1170,'ranged_defense',0,'Ranged Defense'),
 (1171,'ranged_speed',0,'Enhanced Ranged Speed'),
 (1172,'rescue',0,'Rescue'),
 (1173,'resist_creature_attack',0,'Resist Creature Attacks'),
 (1174,'resistance_bleeding',0,'Bleeding Resistance'),
 (1175,'resistance_disease',0,'Disease Resistance'),
 (1176,'resistance_fire',0,'Fire Resistance'),
 (1177,'resistance_poison',0,'Poison Resistance'),
 (1178,'resistance_states',0,'States Resistance'),
 (1179,'resistcreatureattack',0,'Resist Creature Attacks'),
 (1180,'reverse_engineering',0,'Reverse Engineering'),
 (1181,'ridingmount',0,'Riding Mount'),
 (1182,'rifle_accuracy',0,'Rifle Accuracy'),
 (1183,'rifle_aim',0,'Rifle Aiming'),
 (1184,'rifle_concealment_chance',0,'Rifle Concealment Chance'),
 (1185,'rifle_counterattack',0,'Rifle Counterattacks'),
 (1186,'rifle_crawl',0,'Rifle Crawl Speed'),
 (1187,'rifle_damage',0,'Rifle Damage'),
 (1188,'rifle_hit_while_moving',0,'Rifle Accuracy While Moving'),
 (1189,'rifle_kneeling',0,'Rifle Accuracy While Kneeling'),
 (1190,'rifle_prone',0,'Rifle Accuracy While Prone'),
 (1191,'rifle_speed',0,'Rifle Speed'),
 (1192,'rifle_standing',0,'Rifle Accuracy While Standing'),
 (1193,'saber_block',0,'Lightsaber Block'),
 (1194,'sales',0,'Sales'),
 (1195,'shields_assembly',0,'Shields Assembly'),
 (1196,'shields_experimentation',0,'Shield Experimentation'),
 (1197,'shop_sign',0,'Shop Sign Options'),
 (1198,'slice_market',0,'Slicing'),
 (1199,'slope_move',0,'Terrain Negotiation'),
 (1200,'spice_assembly',0,'Spice Assembly'),
 (1201,'spice_experimentation',0,'Spice Experimentation'),
 (1202,'steadyaim',0,'Steady Aim Bonus'),
 (1203,'stored_pets',0,'Stored Pets'),
 (1204,'structure_assembly',0,'Structure Assembly'),
 (1205,'structure_complexity',0,'Structure Complexity'),
 (1206,'structure_experimentation',0,'Structure Experimentation'),
 (1207,'structure_maintenance_mod',0,'Structure Maintenance'),
 (1208,'stun_defense',0,'Defense Vs. Stun'),
 (1209,'survey_flora_structural',0,'Flora Surveying'),
 (1210,'survey_flora_structural_range',0,'Flora Surveying Range'),
 (1211,'survey_flora_structural_resolution',0,'Flora Surveying Resolution'),
 (1212,'survey_gas',0,'Gas Surveying'),
 (1213,'survey_gas_range',0,'Gas Surveying Range'),
 (1214,'survey_gas_resolution',0,'Gas Surveying Resolution'),
 (1215,'survey_liquid',0,'Liquid Surveying'),
 (1216,'survey_liquid_range',0,'Liquid Surveying Range'),
 (1217,'survey_liquid_resolution',0,'Liquid Surveying Resolution'),
 (1218,'survey_solid',0,'Mineral Surveying'),
 (1219,'survey_solid_range',0,'Mineral Surveying Range'),
 (1220,'survey_solid_resolution',0,'Mineral Surveying Resolution'),
 (1221,'surveying',0,'Surveying'),
 (1222,'systems_reverse',0,'Systems Reverse Engineering'),
 (1223,'take_cover',0,'Cover'),
 (1224,'takecover',0,'Cover'),
 (1225,'tame_aggro',0,'Taming Vicious Creatures'),
 (1226,'tame_bonus',0,'Creature Taming Bonus'),
 (1227,'tame_level',0,'Max level of pets'),
 (1228,'tame_non_aggro',0,'Taming Wild Creatures'),
 (1229,'taunt',0,'Taunt'),
 (1230,'thrown_accuracy',0,'Thrown Weapon Accuracy'),
 (1231,'thrown_speed',0,'Thrown Weapon Speed'),
 (1232,'tissue_assembly',0,'Tissue Assembly'),
 (1233,'tissue_experimentation',0,'Tissue Experimentation'),
 (1234,'track_creature',0,'Creature Tracking'),
 (1235,'trackcreature',0,'Creature Tracking'),
 (1236,'trapping',0,'Trapping'),
 (1237,'twohandedmelee_accuracy',0,'Two-handed Weapon Accuracy'),
 (1238,'twohandedmelee_counter_attack',0,'Two-handed Weapon Counter Attack'),
 (1239,'twohandedmelee_evasion',0,'Two-handed Weapon Evasion'),
 (1240,'twohandedmelee_speed',0,'Two-handed Weapon Speed'),
 (1241,'twohandedmeleedamage',0,'Two-handed Melee Damage'),
 (1242,'twohandlightsaber_accuracy',0,'Two-handed Lightsaber Accuracy'),
 (1243,'twohandlightsaber_speed',0,'Two-handed Lightsaber Speed'),
 (1244,'twohandlightsaber_toughness',0,'Two-handed Lightsaber Toughness'),
 (1245,'twohandmelee_accuracy',0,'Two-handed Melee Accuracy'),
 (1246,'twohandmelee_center_of_being_efficacy',0,'Two-handed Melee Center Of Being Efficacy'),
 (1247,'twohandmelee_counter_attack',0,'Two-handed Melee Counter Attacks'),
 (1248,'twohandmelee_damage',0,'Two-handed Melee Damage'),
 (1249,'twohandmelee_evasion',0,'Two-handed Melee Evasion'),
 (1250,'twohandmelee_speed',0,'Two-handed Melee Speed'),
 (1251,'twohandmelee_toughness',0,'Two-handed Melee Toughness'),
 (1252,'twohandpolearm',0,'Two Handed Pole Arm'),
 (1253,'twohandtechnique',0,'Two Handed Technique'),
 (1254,'unarmed_accuracy',0,'Unarmed Accuracy'),
 (1255,'unarmed_center_of_being_efficacy',0,'Unarmed Center Of Being Efficacy'),
 (1256,'unarmed_damage',0,'Unarmed Damage');
INSERT INTO `attributes` (`id`,`name`,`internal`,`attribute_internal_description`) VALUES 
 (1257,'unarmed_passive_defense',0,'Defensive Acuity'),
 (1258,'unarmed_speed',0,'Unarmed Speed'),
 (1259,'unarmed_toughness',0,'Unarmed Toughness'),
 (1260,'vendor_item_limit',0,'Vendor Item Limit'),
 (1261,'volley',0,'Volley Fire Bonus'),
 (1262,'warcry',0,'Warcry'),
 (1263,'weapon_assembly',0,'Weapon Assembly'),
 (1264,'weapon_experimentation',0,'Weapon Experimentation'),
 (1265,'weapon_repair',0,'Weapon Repair'),
 (1266,'weapon_systems',0,'Weapon Systems'),
 (1267,'weapon_systems_experimentation',0,'Weapon Systems Experimentation'),
 (1268,'weapon_group',1,'weapon group'),
 (1269,'food_icon',1,'Food Buff Icon'),
 (1270,'insured',1,'Insured Item'),
 (2000,'cat_wpn_damage.wpn_damage_type',0,'Category: Weapon Damage Type'),
 (2001,'cat_wpn_damage.wpn_damage_min',0,'Category: Weapon Damage Min'),
 (2002,'cat_wpn_damage.wpn_damage_max',0,'Category: Weapon Damage Max'),
 (2003,'cat_wpn_damage.wpn_wound_chance',0,'Category: Weapon Wound'),
 (2004,'cat_wpn_rangemods.wpn_range_zero',0,'Category: Weapon Zero Range'),
 (2005,'cat_wpn_rangemods.wpn_range_mid',0,'Category: Weapon Mid Range'),
 (2006,'cat_wpn_rangemods.wpn_range_max',0,'Category: Weapon Max Range'),
 (2007,'cat_wpn_attack_cost.wpn_attack_cost_health',0,'Category: Weapon Health Cost'),
 (2008,'cat_wpn_attack_cost.wpn_attack_cost_action',0,'Category: Weapon Action Cost'),
 (2009,'cat_wpn_attack_cost.wpn_attack_cost_mind',0,'Category: Weapon Mind Cost'),
 (2010,'cat_armor_effectiveness.armor_eff_kinetic',0,'Category: Armor Effectivness (Kinetic)'),
 (2011,'cat_armor_effectiveness.armor_eff_energy',0,'Category: Armor Effectivness (Energy)'),
 (2012,'cat_armor_effectiveness.armor_eff_blast',0,'Category: Armor Effectivness (Blast)'),
 (2013,'cat_armor_effectiveness.armor_eff_stun',0,'Category: Armor Effectivness (Stun)'),
 (2014,'cat_armor_effectiveness.armor_eff_elemental_heat',0,'Category: Armor Effectivness (Heat)'),
 (2015,'cat_armor_effectiveness.armor_eff_elemental_cold',0,'Category: Armor Effectivness (Cold)'),
 (2016,'cat_armor_effectiveness.armor_eff_elemental_acid',0,'Category: Armor Effectivness (Acid)'),
 (2017,'cat_armor_effectiveness.armor_eff_elemental_electrical',0,'Category: Armor Effectivness (Electricity)'),
 (2018,'cat_armor_effectiveness.armor_eff_restraint',0,'Category: Armor Effectivness (Lightsaber)'),
 (2019,'cat_armor_special_protection.armor_eff_kinetic',0,'Category: Armor Special Protection (Kinetic)'),
 (2020,'cat_armor_special_protection.armor_eff_energy',0,'Category: Armor Special Protection (Energy)'),
 (2021,'cat_armor_special_protection.armor_eff_blast',0,'Category: Armor Special Protection (Blast)'),
 (2022,'cat_armor_special_protection.armor_eff_stun',0,'Category: Armor Special Protection (Stun)'),
 (2023,'cat_armor_special_protection.armor_eff_elemental_heat',0,'Category: Armor Special Protection (Heat)'),
 (2024,'cat_armor_special_protection.armor_eff_elemental_cold',0,'Category: Armor Special Protection (Cold)'),
 (2025,'cat_armor_special_protection.armor_eff_elemental_acid',0,'Category: Armor Special Protection (Acid)'),
 (2026,'cat_armor_special_protection.armor_eff_elemental_electrical',0,'Category: Armor Special Protection (Electrical)'),
 (2027,'cat_armor_special_protection.armor_eff_restraint',0,'Category: Armor Special Protection (Lightsaber)'),
 (2028,'cat_armor_vulnerability.armor_eff_kinetic',0,'Category: Armor Vulnerability (Kinetic)'),
 (2029,'cat_armor_vulnerability.armor_eff_energy',0,'Category: Armor Vulnerability (Energy)'),
 (2030,'cat_armor_vulnerability.armor_eff_blast',0,'Category: Armor Vulnerability (Blast)'),
 (2031,'cat_armor_vulnerability.armor_eff_stun',0,'Category: Armor Vulnerability (Stun)'),
 (2032,'cat_armor_vulnerability.armor_eff_elemental_heat',0,'Category: Armor Vulnerability (Heat)'),
 (2033,'cat_armor_vulnerability.armor_eff_elemental_cold',0,'Category: Armor Vulnerability (Cold)'),
 (2034,'cat_armor_vulnerability.armor_eff_elemental_acid',0,'Category: Armor Vulnerability (Acid)'),
 (2035,'cat_armor_vulnerability.armor_eff_elemental_electrical',0,'Category: Armor Vulnerability (Electrical)'),
 (2036,'cat_armor_vulnerability.armor_eff_restraint',0,'Category: Armor Vulnerability (Lightsaber)'),
 (2037,'moutable',1,'Creature: Moutable'),
 (2038,'Herd',1,'Creature: Herd'),
 (2039,'Pack',1,'Creature: Pack'),
 (2040,'Bioengineered',1,'Creature: Bio-Engineered'),
 (2041,'harvest_qty',1,'Creature: Harvesting Quantity (Avg)'),
 (2042,'cant_be_harmed',1,'Creature: Cant Be Harmed'),
 (2043,'healer',1,'Creature: Healer'),
 (2044,'creature_xp',1,'Creature: XP');
/*!40000 ALTER TABLE `attributes` ENABLE KEYS */;




/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
